# Automatically generated by Colaboratory.

# Original file is located at
# https://colab.research.google.com/drive/1o8aXBRikvf-BxM6i5dwDj99W2gWfZQkA


import pandas as pd
import seaborn as sns
import google.colab as files

df_task3 = df[df['Численность студентов, всего человек, 2019'] < 10001]

plot = sns.barplot(df_task3, x = 'Субъект РФ', y = 'Численность студентов заочная форма, человек, 2019')

plot.set_xticklabels(labels = df_task3['Субъект РФ'], rotation = 90)