
# Automatically generated by Colaboratory.

# Original file is located at
# https://colab.research.google.com/drive/1o8aXBRikvf-BxM6i5dwDj99W2gWfZQkA


import pandas as pd
import seaborn as sns
import google.colab as files

# Задача 2. Постройте диаграмму с данными о численности студентов дневной формы обучения южного федерального округа за 2017 год.

df_task2 = df.iloc[33:41,:]

plot = sns.barplot(df_task2, x = 'Субъект РФ', y = 'Численность студентов, очная форма, человек, 2017')

plot.set_xticklabels(labels = df_task2['Субъект РФ'], rotation = 90)