
# Automatically generated by Colaboratory.

# Original file is located at
# https://colab.research.google.com/drive/1o8aXBRikvf-BxM6i5dwDj99W2gWfZQkA


import pandas as pd
import seaborn as sns
import google.colab as files

# Задача 1. Найдите, какая область центрального федерального округа имела 
# наибольшую численность студентов вечерней формы обучения в 2015 году.


df = pd.read_csv('data20152019.csv', sep=';', encoding='cp1251')
df_task1 = df.iloc[2:20,:]

maxvalue = df_task1['Численность студентов очно-заочная (вечерняя) форма, человек, 2015'].max()

df_task1[df_task1['Численность студентов очно-заочная (вечерняя) форма, человек, 2015'] == maxvalue]